server:
  port: 8088

spring:
  application:
    name: NOTIFICATION-SERVICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: NotificationServiceHikariPool
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: com.techhub.app.commonservice.jpa.PostgreSQLEnumDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-service-v3
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOTIFICATION_MAIL_USERNAME:}
    password: ${NOTIFICATION_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://${HOST_IP_ADDRESS:localhost}:9411/}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:https://eureka.tonynyan.id.vn/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s

logging:
  level:
    com.techhub.app.notificationservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  topics:
    email: ${KAFKA_EMAIL_TOPIC}
    notification: ${KAFKA_NOTIFICATION_TOPIC}
  consumer:
    group-id: notification-service-v3
    concurrency: ${KAFKA_CONSUMER_CONCURRENCY}
    ack-mode: ${KAFKA_CONSUMER_ACK_MODE}
    trusted-packages: ${KAFKA_CONSUMER_TRUSTED_PACKAGES}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
