spring:
  config:
    activate:
      on-profile: prod
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: src/main/resources/script/prod_log.log
    clean-history-on-start: false
  level:
    org:
      hibernate.SQL: INFO
      springframework.web: INFO
      springframework.data: INFO
      boot.autoconfigure.data.rest: INFO
      boot.autoconfigure.data.jpa: INFO
      boot.autoconfigure.orm: INFO