spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/techhub}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: com.techhub.app.commonservice.jpa.PostgreSQLEnumDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:103.188.83.154:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:blog-service}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:latest}
      properties:
        spring.json.trusted.packages: ${KAFKA_CONSUMER_TRUSTED_PACKAGES:*}

logging:
  level:
    com.techhub.app.blogservice: DEBUG

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:103.188.83.154:9092}
  topics:
    email: ${KAFKA_EMAIL_TOPIC:email-notifications}
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP:blog-service}
    concurrency: ${KAFKA_CONSUMER_CONCURRENCY:3}
    ack-mode: ${KAFKA_CONSUMER_ACK_MODE:MANUAL_IMMEDIATE}
    trusted-packages: ${KAFKA_CONSUMER_TRUSTED_PACKAGES:*}
