
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:postgresql://localhost:5432/techhub_web_db
    username: postgres
    password: 30102004
  #  session:
  #    store-type: redis
  #    redis:
  #      namespace: "spring:session:dbiz"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
#  redis:
#    url: jdbc:redis://172.16.3.4:6379
#    host: 172.16.3.4
#    port: 6379
#    username: default
#    password: Oracle@123
logging:
  file:
    name: src/main/resources/script/dev_log.log
    clean-history-on-start: false
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
      boot:
        autoconfigure:
          data:
            rest: INFO
            jpa: INFO
            orm: INFO

