
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jackson:
    serialization:
      indent-output: true

#  session:
#    store-type: redis
#    redis:
#      namespace: "spring:session:dbiz"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
#  redis:
#    url: jdbc:redis://172.16.3.4:6379
#    host: 172.16.3.4
#    port: 6379
#    username: default
#    password: Oracle@123

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://${HOST_IP_ADDRESS:localhost}:8761/eureka}
  instance:
    ip-address: ${HOST_IP_ADDRESS:localhost}
    prefer-ip-address: true